[递推最小二乘法](http://www.docin.com/p-1497951884.html)

还有另外一种递推最小二乘是利用过去的输入输出去预测新的输出，并不是同一种算法

设方程$x_kA=b_k$，$x_k$为n维输入变量，$b_k$为输出，$A$为n维待辨识参数

实际$b_k$存在测量误差情况下，$Ax_k=b_k+\xi_k$

设$n=3$，$A=[1,2,3]$，生成测试数据

In [73]:
import numpy as np

n = 3
A = np.matrix([1,2,3]).T
x = []
b = []
for i in range(500):
    xi = np.matrix((np.random.rand(n)-0.5)*10)
    x.append(xi)
    b.append(xi.dot(A)[0,0]+(np.random.rand()-0.5))

**最小二乘**

In [84]:
X = np.matrix(np.vstack(x))
A = (np.linalg.inv(X.T.dot(X)).dot(X.T))*np.matrix(b).T
print(A)

[[ 0.99562951]
 [ 1.98711778]
 [ 2.99843311]]


**递推最小二乘**

In [106]:
lbd = 1.0

def Pnext(xk, Qk, Pk):
    return 1.0/lbd*(np.eye(n)-Qk.dot(xk)).dot(Pk)

def Qk(xk, Pk):
    return Pk.dot(xk.T)/(lbd+xk.dot(Pk).dot(xk.T))

Ai = np.matrix([0,0,0]).T
Pi = np.eye(n)*1000000
for i in range(len(x)):
    bi = b[i]
    xi = x[i]
    Qi = Qk(xi, Pi)
    Ai = Ai+Qi.dot(bi-xi.dot(Ai))
    Pi = Pnext(xi,Qi,Pi)
print(Ai)

[[ 0.99562951]
 [ 1.98711778]
 [ 2.99843311]]


In [102]:
print(Qi)
print(xi)
print(Qi.dot(xi))

[[ 0.00065313]
 [-0.00075494]
 [-0.00072897]]
[[ 3.1103628  -2.984917   -3.00911299]]
[[ 0.00203148 -0.00194955 -0.00196535]
 [-0.00234814  0.00225344  0.0022717 ]
 [-0.00226735  0.00217591  0.00219354]]
